# Generated by Django 4.0.3 on 2022-12-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_automobilevo_salescustomer_salesrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescustomer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
