# Generated by Django 4.0.3 on 2022-12-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_rename_customer_salesrecord_sales_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='import_href',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
