# Generated by Django 4.0.3 on 2022-12-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0010_automobilevo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
