# Generated by Django 4.0.3 on 2022-12-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_remove_appointment_automobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='color',
            field=models.CharField(default='red', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='year',
            field=models.PositiveSmallIntegerField(default=1997),
            preserve_default=False,
        ),
    ]
