# Generated by Django 4.0.3 on 2022-12-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_automobilevo_color_automobilevo_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='year',
        ),
    ]
